# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fanyi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fanyi.proto',
  package='fanyi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x66\x61nyi.proto\x12\x05\x66\x61nyi\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04text\x18\x01 \x01(\t26\n\tTranslate\x12)\n\x0b\x44oTranslate\x12\x0b.fanyi.Data\x1a\x0b.fanyi.Data\"\x00\x62\x06proto3')
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='fanyi.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='fanyi.Data.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'fanyi_pb2'
  # @@protoc_insertion_point(class_scope:fanyi.Data)
  ))
_sym_db.RegisterMessage(Data)



_TRANSLATE = _descriptor.ServiceDescriptor(
  name='Translate',
  full_name='fanyi.Translate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=44,
  serialized_end=98,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoTranslate',
    full_name='fanyi.Translate.DoTranslate',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSLATE)

DESCRIPTOR.services_by_name['Translate'] = _TRANSLATE

# @@protoc_insertion_point(module_scope)
