# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import fanyi_pb2 as fanyi__pb2


class TranslateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoTranslate = channel.unary_unary(
        '/fanyi.Translate/DoTranslate',
        request_serializer=fanyi__pb2.Data.SerializeToString,
        response_deserializer=fanyi__pb2.Data.FromString,
        )


class TranslateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoTranslate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TranslateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoTranslate': grpc.unary_unary_rpc_method_handler(
          servicer.DoTranslate,
          request_deserializer=fanyi__pb2.Data.FromString,
          response_serializer=fanyi__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fanyi.Translate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
